#!/usr/bin/env node

/**
 * FoodAgent — Restaurant Procurement AI Agent Client
 * Demonstrates an external AI agent consuming MamaPrice Commerce Intelligence via Base x402
 */

const API_BASE = process.env.MAMAPRICE_API_URL || "http://localhost:3001";

export async function runFoodAgent({ product = "tomatoes", location = "Lagos", verbose = true } = {}) {
  const log = (...args) => verbose && console.log("[FoodAgent]", ...args);
  log(`🤖 FoodAgent initialized. Goal: Query ${product} prices in ${location} for procurement planning.`);

  // Step 1: Initial query without payment proof
  log(`Step 1: Requesting GET /api/v1/commerce/prices?product=${product}&location=${location}...`);
  const initialRes = await fetch(`${API_BASE}/api/v1/commerce/prices?product=${encodeURIComponent(product)}&location=${encodeURIComponent(location)}`);

  if (initialRes.status !== 402) {
    const data = await initialRes.json();
    log(`Received non-402 response status ${initialRes.status}:`, data);
    return { success: false, status: initialRes.status, data };
  }

  const challenge = await initialRes.json();
  log("Step 2: Received HTTP 402 Payment Required challenge from MamaPrice:");
  log(JSON.stringify(challenge?.challenge?.payment || challenge, null, 2));

  // Step 3: Construct Base USDC payment proof
  log("Step 3: Constructing Base x402 payment proof...");
  const txHash = `0x_base_tx_food_agent_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`;
  const paymentProof = {
    transactionHash: txHash,
    chain: challenge?.challenge?.payment?.network || "Base",
    currency: challenge?.challenge?.payment?.currency || "USDC",
    amount: challenge?.challenge?.payment?.amount || 0.01,
    method: "x402",
  };

  // Step 4: Replay request with payment proof
  log("Step 4: Replaying request with Base USDC x402 payment proof...");
  const replayRes = await fetch(
    `${API_BASE}/api/v1/commerce/prices?product=${encodeURIComponent(product)}&location=${encodeURIComponent(location)}&transactionHash=${paymentProof.transactionHash}&chain=${paymentProof.chain}&currency=${paymentProof.currency}&amount=${paymentProof.amount}&method=${paymentProof.method}`
  );

  const finalData = await replayRes.json();
  if (replayRes.status === 200) {
    log("Step 5: ✅ Payment verified by MamaPrice API! Received grounded commerce intelligence:");
    log(`Product: ${finalData.product} | Location: ${finalData.location}`);
    log(`Grounded By: ${finalData.grounded_by} | Generated By: ${finalData.generated_by}`);
    log(`Intelligence Output:\n${finalData.response}`);
    return { success: true, status: 200, data: finalData, challenge, paymentProof };
  } else {
    log(`Step 5: ❌ Replay failed with status ${replayRes.status}:`, finalData);
    return { success: false, status: replayRes.status, data: finalData };
  }
}

if (process.argv[1] && process.argv[1].includes("FoodAgent.js")) {
  runFoodAgent().catch(err => {
    console.error("FoodAgent error:", err);
    process.exit(1);
  });
}
