#!/usr/bin/env node

/**
 * Phase 2 — External AI Agent Integration Test Suite
 */

import { runFoodAgent } from "./agents/FoodAgent.js";
import { runMarketMonitor } from "./agents/MarketMonitor.js";

let totalTests = 0;
let passedTests = 0;
let failedTests = 0;

function assert(condition, message) {
  totalTests++;
  if (condition) {
    console.log(`  ✅ PASS: ${message}`);
    passedTests++;
  } else {
    console.error(`  ❌ FAIL: ${message}`);
    failedTests++;
  }
}

async function runSuite() {
  console.log("==========================================================");
  console.log("⚡ Starting Phase 2 — External AI Agent Integration Test Suite");
  console.log("==========================================================");

  // Test 1: Run FoodAgent (Restaurant Procurement Agent)
  console.log("\n[Test 1] Running FoodAgent (Restaurant Procurement Flow)...");
  const foodResult = await runFoodAgent({ product: "tomatoes", location: "Lagos", verbose: false });
  assert(foodResult.success === true, "FoodAgent executed successfully with 200 OK");
  assert((foodResult.challenge?.code || foodResult.challenge?.challenge?.code) === "x402", "FoodAgent received valid x402 challenge");

  assert(foodResult.paymentProof?.chain === "Base", "FoodAgent constructed Base payment proof");
  assert(foodResult.data?.product === "tomatoes", "FoodAgent response product matches query");
  assert(foodResult.data?.grounded_by === "OjaGraph", "FoodAgent response grounded by OjaGraph");
  assert(foodResult.data?.generated_by === "OjaLM", "FoodAgent response generated by OjaLM");

  // Test 2: Replay protection against FoodAgent payment proof
  console.log("\n[Test 2] Replay attack verification on FoodAgent payment proof...");
  const replayRes = await fetch(
    `http://localhost:3001/api/v1/commerce/prices?product=tomatoes&location=Lagos&transactionHash=${foodResult.paymentProof.transactionHash}&chain=Base&currency=USDC&amount=0.01&method=x402`
  );
  assert(replayRes.status === 409, `Expected status 409 Conflict for replayed proof, got ${replayRes.status}`);

  // Test 3: Run MarketMonitor (Multi-Market Comparison Agent)
  console.log("\n[Test 3] Running MarketMonitor (Multi-Market Comparison Flow)...");
  const monitorResult = await runMarketMonitor({ product: "rice", markets: ["Lagos", "Ibadan", "Kano"], verbose: false });
  assert(monitorResult.success === true, "MarketMonitor successfully queried and paid for all 3 markets");
  assert(monitorResult.results.length === 3, "MarketMonitor returned 3 market data records");
  assert(monitorResult.results.every(r => r.paymentRecord?.transactionHash), "Every market record contains a verified Base payment proof");

  console.log("\n==========================================================");
  console.log(`📊 Phase 2 Test Summary: ${passedTests}/${totalTests} Passed (${failedTests} Failed)`);
  console.log("==========================================================");

  if (failedTests > 0) {
    process.exit(1);
  }
}

runSuite().catch(err => {
  console.error("Phase 2 test suite fatal error:", err);
  process.exit(1);
});
